### PR TITLE
Curses are opt-in and customizable

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
This builds on the changes in https://github.com/hackclub/scrappy/pull/237. It's an example implementation that allows for:
- mild vs spicy responses (words scrappy already says vs words that are added in 237)
- custom responses per trigger word (ex. 'f**ck' can trigger specific responses that other trigger words won't have)
- user opt-in (see `triggerSpicyOptIn` in transcript.yml)

**Comment by maxwofford** [comment]
Also, includes some new insults that i think are closer to scrappy's tone. Not sure if i hit the right cord here-- I haven't written scrappy copy in a while.
ex. 'fuck' triggers 'go suck a duck' & '_GET OFF MY CHEEKS USER_'

EDIT: you can add others in a similar way in transcript.yml

**Comment by quackduck** [comment]
IMO `crappy` and `crap` are mild, and you can add "dummy" to the mild list too.

**Comment by cole-wilson** [comment]
I think it's worth mentioning that just because it's opt-in doesn't mean other people won't see it. I feel like insults like these might be a little off-putting for users who don't opt-in, especially new hack clubbers.

**Comment by maxwofford** [comment]
@cole-wilson check out the copy changes in this PR (transcript.yml)-- i tried to make them more along the lines of how scrappy would talk.

If you have any suggestions I'm open to them!

**Comment by maxwofford** [comment]
@l3gacyb3ta thoughts on this?

**Comment by l3gacyb3ta** [comment]
Oooo i like the idea!

**Review by l3gacyb3ta — APPROVED** [review]
Dang cool!

**Pull request merged**
